version: '3'


services:
  web:
    build:
      context: .
    image: ghcr.io/reflejar/pis:1.1.3
    ports:
      - 3000:80

  censos: 
    image: ghcr.io/reflejar/pis-dash:latest
    ports:
      - "8050:8050"
    command: python main.py indicadores_censos
  
  ranking: 
    image: ghcr.io/reflejar/pis-dash:latest
    ports:
      - "8050:8050"      
    command: python main.py ranking_ambiental
  
  zonificacion: 
    image: ghcr.io/reflejar/pis-dash:latest
    ports:
      - "8050:8050"      
    command: python main.py mapa_normativo

  shiny: # Aplicaciones hechas en shiny
    # image: ghcr.io/reflejar/pis-shiny:latest
    image: ghcr.io/democraciaenred/pis-shiny:latest
    ports:
      - "3838:3838"