version: '3'


services:
  web:
    build:
      context: .
    # image: ghcr.io/reflejar/pis-web:latest
    image: ghcr.io/democraciaenred/pis:1.1.3
    ports:
      - 3000:80

  dash: # Aplicaciones hechas en python
    # image: ghcr.io/reflejar/pis-dash:latest
    image: ghcr.io/democraciaenred/pis-dash:1.0.0-beta2
    ports:
      - "8050:8050"

  shiny: # Aplicaciones hechas en shiny
    # image: ghcr.io/reflejar/pis-shiny:latest
    image: ghcr.io/democraciaenred/pis-shiny:1.0.0-beta1
    ports:
      - "3838:3838"